import math
print('Выберете необходимую функцию из списка: сложение, вычитание, умножение, деление, степень, логарифм, округление.')
op = input()
if op.lower() == 'сложение':
    print('Введите первое слогаемое')
    s1 = int(input())
    print ('Введите второе слогаемое')
    s2 = int(input())
    print('Сумма')
    print( s1 + s2 )
elif op.lower() == 'вычитание':
    print('Введите уменьшаемое')
    um = int(input())
    print ('Введите вычитаемое')
    ve = int(input())
    print('Разность')
    print( um - ve )
elif op.lower() == 'умножение':
    print('Введите первый множитель')
    m1 = int(input())
    print ('Введите второй множитель')
    m2 = int(input())
    print('Произведение')
    print( m1 * m2 )
elif op.lower() == 'деление':
    print('Введите делимое')
    dell = int(input())
    print ('Введите делитель отличный от нуля')
    delli = int(input())
    print('Частное')
    print( dell / delli )
elif op.lower() == 'степень':
    print('Введите число')
    ch = int(input())
    print ('Введите степень')
    st = int(input())
    print('Степень')
    print( ch ** st )
elif op.lower() == 'логарифм':
    print('Введите значение логарифма')
    lg = int(input())
    print('Введите основание логарифма')
    osn = int(input())
    print('Показатель степени равен')
    print( math.log(lg,osn))
elif op.lower() == 'округление':
    print('Введите число')
    nu = float(input())
    print('Введите колличество знаков после запятой')
    pz = int(input())
    print('Результат')
    print(round(nu, pz))
